# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: method hospitality
destination: ./_site
exclude:
  - package.json
  - Gruntfile.js
  - node_modules
  - README.md
gems:
  - jekyll-sitemap
keys:
  ga: UA-XXXXXXXX-1
name: METHOD HOSPITALITY
permalink: pretty
source: .
timezone: America/New_York
url: http://www.methodhospitality.com
